name: AdaptCulture
favicon: null
layout_spectrum: 0.02355
typography_spectrum: 0.9955
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2a233'
    - '#333333'
    - '#261f18'
    - '#36332e'
    - '#ea9c31'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
