name: AdaptCulture
favicon: null
layout_spectrum: 0.02355048037134111
typography_spectrum: 0.7895967785734683
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5088984677568078
  lightness: 0.007690879050642252
  saturation: 0.39030171325430274
  rhythmicContrast: 0.36926722782664
purpose: []
